<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Str;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
              "id" => 1,
              "title" => "1 Liter Liquid black soap with tea tree essential oil",
              "slug" => "1-liter-liquid-black-soap-with-tea-tree-essential-oil",
              "product_code" => 10102,
              "featured" => 0,
              "buying_price" => "1200.00",
              "selling_price" => "2250.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 10,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:21:05"
            ],
            [
              "id" => 3,
              "title" => "100ml Aloe Vera",
              "slug" => "100ml-aloe-vera",
              "product_code" => 63,
              "featured" => 0,
              "buying_price" => "240.00",
              "selling_price" => "600.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 24,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:21:28"
            ],
            [
              "id" => 4,
              "title" => "1kg Black Soap",
              "slug" => "1kg-black-soap",
              "product_code" => 27,
              "featured" => 0,
              "buying_price" => "860.00",
              "selling_price" => "1700.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 25,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:21:41"
            ],
            [
              "id" => 5,
              "title" => "200g (Strawberry) whipped",
              "slug" => "200g-strawberry-whipped",
              "product_code" => 10072,
              "featured" => 0,
              "buying_price" => "250.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:21:51"
            ],
            [
              "id" => 6,
              "title" => "200g Shea & Cocoa (Sweet Orange)",
              "slug" => "200g-shea-cocoa-sweet-orange",
              "product_code" => 56,
              "featured" => 0,
              "buying_price" => "405.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:22:05"
            ],
            [
              "id" => 7,
              "title" => "200g unscented (new)",
              "slug" => "200g-unscented-new",
              "product_code" => 58,
              "featured" => 0,
              "buying_price" => "353.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:22:17"
            ],
            [
              "id" => 8,
              "title" => "200g Whipped Shea(Vanilla)",
              "slug" => "200g-whipped-sheavanilla",
              "product_code" => 10090,
              "featured" => 0,
              "buying_price" => "320.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => 200,
              "product_order" => 200,
              "stock_count" => 25,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:22:38"
            ],
            [
              "id" => 9,
              "title" => "250g Black Soap",
              "slug" => "250g-black-soap",
              "product_code" => 1,
              "featured" => 0,
              "buying_price" => "200.00",
              "selling_price" => "500.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 50,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:22:53"
            ],
            [
              "id" => 11,
              "title" => "3in1 Clay Mask",
              "slug" => "3in1-clay-mask",
              "product_code" => 10115,
              "featured" => 0,
              "buying_price" => "155.00",
              "selling_price" => "500.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 3,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:23:09"
            ],
            [
              "id" => 13,
              "title" => "400g (Strawberry) whipped",
              "slug" => "400g-strawberry-whipped",
              "product_code" => 10068,
              "featured" => 1,
              "buying_price" => "480.00",
              "selling_price" => "1150.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 30,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:23:29"
            ],
            [
              "id" => 14,
              "title" => "400g Unscented",
              "slug" => "400g-unscented",
              "product_code" => 62,
              "featured" => 0,
              "buying_price" => "500.00",
              "selling_price" => "1150.00",
              "discount_price" => "0.00",
              "product_measurement" => 400,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:24:06"
            ],
            [
              "id" => 15,
              "title" => "5 Liter Liquid Soap",
              "slug" => "5-liter-liquid-soap",
              "product_code" => 10071,
              "featured" => 0,
              "buying_price" => "3250.00",
              "selling_price" => "8000.00",
              "discount_price" => "8000.00",
              "product_measurement" => 5,
              "product_order" => 200,
              "stock_count" => 5,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:24:27"
            ],
            [
              "id" => 18,
              "title" => "Atlas Cedarwood",
              "slug" => "atlas-cedarwood",
              "product_code" => 14,
              "featured" => 0,
              "buying_price" => "343.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 10,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:25:12"
            ],
            [
              "id" => 19,
              "title" => "Avocado oil",
              "slug" => "avocado-oil",
              "product_code" => 35,
              "featured" => 0,
              "buying_price" => "159.00",
              "selling_price" => "400.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 30,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:25:35"
            ],
            [
              "id" => 20,
              "title" => "Baby butter",
              "slug" => "baby-butter",
              "product_code" => 74,
              "featured" => 0,
              "buying_price" => "425.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 45,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:26:03"
            ],
            [
              "id" => 22,
              "title" => "Baobab oil 60ml (new)",
              "slug" => "baobab-oil-60ml-new",
              "product_code" => 34,
              "featured" => 0,
              "buying_price" => "400.00",
              "selling_price" => "700.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 24,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:26:22"
            ],
            [
              "id" => 23,
              "title" => "Black Castor Oil",
              "slug" => "black-castor-oil",
              "product_code" => 64,
              "featured" => 0,
              "buying_price" => "470.00",
              "selling_price" => "650.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:27:06"
            ],
            [
              "id" => 24,
              "title" => "Body Elixir( Stretchmarks oil) 100ml",
              "slug" => "body-elixir-stretchmarks-oil-100ml",
              "product_code" => 10096,
              "featured" => 0,
              "buying_price" => "600.00",
              "selling_price" => "1000.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 50,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:27:34"
            ],
            [
              "id" => 27,
              "title" => "Cocoa 1kg",
              "slug" => "cocoa-1kg",
              "product_code" => 23,
              "featured" => 0,
              "buying_price" => "1000.00",
              "selling_price" => "2000.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 10,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:27:55"
            ],
            [
              "id" => 29,
              "title" => "Cocoa 500g",
              "slug" => "cocoa-500g",
              "product_code" => 10005,
              "featured" => 0,
              "buying_price" => "400.00",
              "selling_price" => "1250.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 12,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:28:12"
            ],
            [
              "id" => 31,
              "title" => "Coffee Scrub",
              "slug" => "coffee-scrub",
              "product_code" => 10101,
              "featured" => 0,
              "buying_price" => "390.00",
              "selling_price" => "1000.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:28:58"
            ],
            [
              "id" => 32,
              "title" => "Eucalyptus",
              "slug" => "eucalyptus",
              "product_code" => 10112,
              "featured" => 0,
              "buying_price" => "400.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 10,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:29:25"
            ],
            [
              "id" => 33,
              "title" => "Frankincense",
              "slug" => "frankincense",
              "product_code" => 10111,
              "featured" => 0,
              "buying_price" => "400.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 10,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:29:51"
            ],
            [
              "id" => 34,
              "title" => "Geranium",
              "slug" => "geranium",
              "product_code" => 10113,
              "featured" => 0,
              "buying_price" => "400.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 5,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:30:33"
            ],
            [
              "id" => 35,
              "title" => "Ghana 500g",
              "slug" => "ghana-500g",
              "product_code" => 10122,
              "featured" => 0,
              "buying_price" => "500.00",
              "selling_price" => "1000.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 25,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:30:54"
            ],
            [
              "id" => 38,
              "title" => "Grapeseed Oil 100ml",
              "slug" => "grapeseed-oil-100ml",
              "product_code" => 10088,
              "featured" => 0,
              "buying_price" => "500.00",
              "selling_price" => "950.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:31:13"
            ],
            [
              "id" => 39,
              "title" => "Hair Growth butter 200g",
              "slug" => "hair-growth-butter-200g",
              "product_code" => 10097,
              "featured" => 0,
              "buying_price" => "690.00",
              "selling_price" => "1000.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 24,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:31:56"
            ],
            [
              "id" => 40,
              "title" => "Hair Oil",
              "slug" => "hair-oil",
              "product_code" => 10054,
              "featured" => 0,
              "buying_price" => "230.00",
              "selling_price" => "750.00",
              "discount_price" => "750.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:32:49"
            ],
            [
              "id" => 42,
              "title" => "Honey Liquid Black soap",
              "slug" => "honey-liquid-black-soap",
              "product_code" => 81,
              "featured" => 0,
              "buying_price" => "222.00",
              "selling_price" => "400.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 30,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:33:18"
            ],
            [
              "id" => 43,
              "title" => "Hyaluronic Serum",
              "slug" => "hyaluronic-serum",
              "product_code" => 10106,
              "featured" => 0,
              "buying_price" => "380.00",
              "selling_price" => "1000.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:35:13"
            ],
            [
              "id" => 44,
              "title" => "Jojoba oil 100ml",
              "slug" => "jojoba-oil-100ml",
              "product_code" => 10084,
              "featured" => 0,
              "buying_price" => "550.00",
              "selling_price" => "950.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 10,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:36:09"
            ],
            [
              "id" => 47,
              "title" => "Lavender Essential Oil",
              "slug" => "lavender-essential-oil",
              "product_code" => 86,
              "featured" => 0,
              "buying_price" => "230.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 10,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:38:45"
            ],
            [
              "id" => 48,
              "title" => "Lavender 200g (Whipped Body Butter)",
              "slug" => "lavender-200g-whipped-body-butter",
              "product_code" => 10117,
              "featured" => 0,
              "buying_price" => "250.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 15,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:34:14"
            ],
            [
              "id" => 49,
              "title" => "Lavender 400g (Whipped Body Butter)",
              "slug" => "lavender-400g-whipped-body-butter",
              "product_code" => 10116,
              "featured" => 0,
              "buying_price" => "450.00",
              "selling_price" => "1150.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:37:45"
            ],
            [
              "id" => 50,
              "title" => "Lavender Foaming Scrub",
              "slug" => "lavender-foaming-scrub",
              "product_code" => 10120,
              "featured" => 0,
              "buying_price" => "380.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 15,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:38:20"
            ],
            [
              "id" => 53,
              "title" => "Lemongrass",
              "slug" => "lemongrass",
              "product_code" => 18,
              "featured" => 0,
              "buying_price" => "289.47",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 10,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:39:10"
            ],
            [
              "id" => 54,
              "title" => "Lemongrass 200g (Whipped Body Butter)",
              "slug" => "lemongrass-200g-whipped-body-butter",
              "product_code" => 10119,
              "featured" => 0,
              "buying_price" => "250.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 15,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:39:48"
            ],
            [
              "id" => 55,
              "title" => "Lemongrass 400g (Whipped Body Butter)",
              "slug" => "lemongrass-400g-whipped-body-butter",
              "product_code" => 10118,
              "featured" => 0,
              "buying_price" => "450.00",
              "selling_price" => "1150.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:40:15"
            ],
            [
              "id" => 57,
              "title" => "Liquid black soap - Tea Tree",
              "slug" => "liquid-black-soap-tea-tree",
              "product_code" => 3,
              "featured" => 0,
              "buying_price" => "248.00",
              "selling_price" => "650.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 40,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:40:57"
            ],
            [
              "id" => 58,
              "title" => "Niacinamide Serum",
              "slug" => "niacinamide-serum",
              "product_code" => 10107,
              "featured" => 0,
              "buying_price" => "380.00",
              "selling_price" => "1000.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:41:38"
            ],
            [
              "id" => 59,
              "title" => "Peppermint Essential Oil",
              "slug" => "peppermint-essential-oil",
              "product_code" => 10114,
              "featured" => 0,
              "buying_price" => "400.00",
              "selling_price" => "750.00",
              "discount_price" => "500.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 10,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-05 18:41:32"
            ],
            [
              "id" => 60,
              "title" => "Peppermint Foaming Scrub",
              "slug" => "peppermint-foaming-scrub",
              "product_code" => 10121,
              "featured" => 0,
              "buying_price" => "380.00",
              "selling_price" => "750.00",
              "discount_price" => "490.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-05 18:42:18"
            ],
            [
              "id" => 61,
              "title" => "Retinol Serum",
              "slug" => "retinol-serum",
              "product_code" => 10109,
              "featured" => 0,
              "buying_price" => "380.00",
              "selling_price" => "1000.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:46:57"
            ],
            [
              "id" => 63,
              "title" => "Rose Water",
              "slug" => "rose-water",
              "product_code" => 60,
              "featured" => 0,
              "buying_price" => "150.00",
              "selling_price" => "300.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 30,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:46:37"
            ],
            [
              "id" => 64,
              "title" => "Rosehip oil 100ml",
              "slug" => "rosehip-oil-100ml",
              "product_code" => 10086,
              "featured" => 0,
              "buying_price" => "550.00",
              "selling_price" => "950.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:46:17"
            ],
            [
              "id" => 67,
              "title" => "Salicylic Serum",
              "slug" => "salicylic-serum",
              "product_code" => 10108,
              "featured" => 0,
              "buying_price" => "380.00",
              "selling_price" => "1000.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 20,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:45:58"
            ],
            [
              "id" => 68,
              "title" => "Scented Mango Butter",
              "slug" => "scented-mango-butter",
              "product_code" => 10067,
              "featured" => 0,
              "buying_price" => "300.00",
              "selling_price" => "1000.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 0,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:45:38"
            ],
            [
              "id" => 69,
              "title" => "Shea 1 kg Ghana",
              "slug" => "shea-1-kg-ghana",
              "product_code" => 10077,
              "featured" => 0,
              "buying_price" => "800.00",
              "selling_price" => "1700.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 30,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:45:16"
            ],
            [
              "id" => 70,
              "title" => "Shea 1kg Nilotica",
              "slug" => "shea-1kg-nilotica",
              "product_code" => 10002,
              "featured" => 1,
              "buying_price" => "700.00",
              "selling_price" => "1200.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 50,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:44:35"
            ],
            [
              "id" => 71,
              "title" => "Shea 350g Nilotica",
              "slug" => "shea-350g-nilotica",
              "product_code" => 10003,
              "featured" => 0,
              "buying_price" => "319.00",
              "selling_price" => "550.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 50,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:44:12"
            ],
            [
              "id" => 73,
              "title" => "Shea Vanilla 400g",
              "slug" => "shea-vanilla-400g",
              "product_code" => 10089,
              "featured" => 1,
              "buying_price" => "450.00",
              "selling_price" => "1150.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 35,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:43:41"
            ],
            [
              "id" => 74,
              "title" => "Sweet Myrrh",
              "slug" => "sweet-myrrh",
              "product_code" => 10110,
              "featured" => 0,
              "buying_price" => "400.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 10,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:43:21"
            ],
            [
              "id" => 75,
              "title" => "Sweet Orange Essential Oil",
              "slug" => "sweet-orange-essential-oil",
              "product_code" => 17,
              "featured" => 0,
              "buying_price" => "274.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 10,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:42:54"
            ],
            [
              "id" => 76,
              "title" => "Tea Tree Essential Oil",
              "slug" => "tea-tree-essential-oil",
              "product_code" => 15,
              "featured" => 0,
              "buying_price" => "337.00",
              "selling_price" => "750.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 10,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:42:37"
            ],
            [
              "id" => 78,
              "title" => "Vitamin C serum",
              "slug" => "vitamin-c-serum",
              "product_code" => 10095,
              "featured" => 0,
              "buying_price" => "308.00",
              "selling_price" => "1000.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 40,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:42:16"
            ],
            [
              "id" => 79,
              "title" => "Vitamin E",
              "slug" => "vitamin-e",
              "product_code" => 30,
              "featured" => 0,
              "buying_price" => "200.00",
              "selling_price" => "400.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 40,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-04 18:28:17",
              "updated_at" => "2024-04-06 16:41:59"
            ],
            [
              "id" => 80,
              "title" => "400g Shea & Cocoa (Sweet Orange)",
              "slug" => "400g-shea-cocoa-sweet-orange",
              "product_code" => 54,
              "featured" => 0,
              "buying_price" => "400.00",
              "selling_price" => "1150.00",
              "discount_price" => "0.00",
              "product_measurement" => null,
              "product_order" => 200,
              "stock_count" => 40,
              "safety_stock" => 0,
              "description" => null,
              "category_id" => null,
              "measurement_id" => null,
              "created_at" => "2024-04-06 04:50:50",
              "updated_at" => "2024-04-06 16:23:46"
            ]
        ];

        foreach($products as $product) {
            Product::create([
                'title' => $product['title'],
                'slug' => Str::slug($product['title']),
                'product_code' =>$product['product_code'],
                'selling_price' => $product['selling_price'],
                'buying_price' => $product['buying_price'],
                'category_id' => $product['category_id'],
            ]);
        }
    }
}
