version: '3.8'

services:
    # Laravel Backend
    laravel_backend:
        container_name: laravel_backend
        build: .
        volumes:
            - ./:/var/www/html/shea254
        port:
            - "8000:80"
        depends_on:
            - mysql_db


    # MySQL Database
    mysql_db:
        container_name: mysql_db
        image: mysql:8.3.0
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
        - db-data:/var/lib/mysql

    # PhpMyAdmin
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:latest
        ports:
            - "9001:80"
        environment:
            - PMA_ARBITRARY=1

volumes:
    db-data: ~
