# Generated by Django 4.2.7 on 2024-01-02 14:17

import ckeditor_uploader.fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg12345', length=10, max_length=20, prefix='cat', unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('category_order', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/categories')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg12345', length=10, max_length=20, prefix='', unique=True)),
                ('title', models.CharField(default='Product Title', max_length=100, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Product Description', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=999999999999)),
                ('discount_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=999999999999)),
                ('product_status', models.CharField(choices=[('disabled', 'Disabled'), ('published', 'Published')], default='published', max_length=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/product_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='Product.jpg', upload_to='uploads/product_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productsize'),
        ),
    ]
