# Generated by Django 4.2.7 on 2023-12-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=999999999999),
        ),
    ]
