# Generated by Django 4.2.7 on 2023-12-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_new_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
