# Generated by Django 4.2.7 on 2023-12-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category.jpg', upload_to='uploads/categories'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(default='Product.jpg', upload_to='uploads/product_images'),
        ),
    ]
