# Generated by Django 4.2.7 on 2023-12-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_image_alter_productimages_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='uploads/product_images'),
        ),
    ]
