# Generated by Django 4.2.7 on 2023-12-31 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cartorder_cartorderitem_customerinformation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinformation',
            options={'verbose_name_plural': 'Customers Information'},
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customerinformation'),
        ),
    ]
