# Generated by Django 4.2.7 on 2023-12-31 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_customerinformation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customerinformation'),
        ),
    ]
