# Generated by Django 4.2.7 on 2023-12-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cartorder_session_key_alter_cartorder_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='session_key',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
