# Generated by Django 4.2.7 on 2023-12-31 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_cartorder_session_key_cartorder_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='authenticated',
        ),
    ]
