# Generated by Django 4.2.7 on 2023-12-31 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_remove_cartorder_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinformation',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.cartorder'),
        ),
        migrations.AlterField(
            model_name='customerinformation',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerinformation',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerinformation',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerinformation',
            name='last_name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='customerinformation',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
