# Generated by Django 4.2.7 on 2023-12-31 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customerinformation_user_alter_cartorderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinformation',
            name='user',
        ),
    ]
