# Generated by Django 4.2.7 on 2024-01-01 07:59

import core.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_customerinformation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=999999999999),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=core.models.get_default_product_image_path, upload_to='uploads/categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=core.models.get_default_product_image_path, upload_to='uploads/product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=999999999999),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Product Title', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.size'),
        ),
    ]
