# Generated by Django 4.2.7 on 2024-01-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_size_remove_product_new_price_product_discount_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='ProductSize',
        ),
    ]
